// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: complex.proto

/*
Package _gen is a generated protocol buffer package.

It is generated from these files:
	complex.proto
	sendtx.proto
	simple.proto

It has these top-level messages:
	PhoneNumber
	PhoneBook
	Coin
	SendMsg
	IssueMsg
	Tx
	Sig
	Person
	Employee
	Mixed
*/
package _gen

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PhoneNumber struct {
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (m *PhoneNumber) Reset()                    { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()               {}
func (*PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptorComplex, []int{0} }

func (m *PhoneNumber) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type PhoneBook struct {
	Title   string         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Numbers []*PhoneNumber `protobuf:"bytes,2,rep,name=numbers" json:"numbers,omitempty"`
	Random  []int64        `protobuf:"varint,3,rep,packed,name=random" json:"random,omitempty"`
	Codes   []uint32       `protobuf:"fixed32,4,rep,packed,name=codes" json:"codes,omitempty"`
	Views   int32          `protobuf:"varint,5,opt,name=views,proto3" json:"views,omitempty"`
}

func (m *PhoneBook) Reset()                    { *m = PhoneBook{} }
func (m *PhoneBook) String() string            { return proto.CompactTextString(m) }
func (*PhoneBook) ProtoMessage()               {}
func (*PhoneBook) Descriptor() ([]byte, []int) { return fileDescriptorComplex, []int{1} }

func (m *PhoneBook) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PhoneBook) GetNumbers() []*PhoneNumber {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *PhoneBook) GetRandom() []int64 {
	if m != nil {
		return m.Random
	}
	return nil
}

func (m *PhoneBook) GetCodes() []uint32 {
	if m != nil {
		return m.Codes
	}
	return nil
}

func (m *PhoneBook) GetViews() int32 {
	if m != nil {
		return m.Views
	}
	return 0
}

func init() {
	proto.RegisterType((*PhoneNumber)(nil), "_gen.PhoneNumber")
	proto.RegisterType((*PhoneBook)(nil), "_gen.PhoneBook")
}

func init() { proto.RegisterFile("complex.proto", fileDescriptorComplex) }

var fileDescriptorComplex = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2d,
	0xc8, 0x49, 0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x89, 0x4f, 0x4f, 0xcd, 0x53,
	0xb2, 0xe4, 0xe2, 0x0e, 0xc8, 0xc8, 0xcf, 0x4b, 0xf5, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x12, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0xc4, 0xb8, 0xd8, 0xf2, 0xc0, 0xb2, 0x12, 0x4c, 0x60, 0x51, 0x28, 0x4f, 0x69, 0x12, 0x23, 0x17,
	0x27, 0x58, 0xaf, 0x53, 0x7e, 0x7e, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x66, 0x49, 0x0e, 0x4c,
	0x2b, 0x84, 0x23, 0xa4, 0xcd, 0xc5, 0x0e, 0x51, 0x5d, 0x2c, 0xc1, 0xa4, 0xc0, 0xac, 0xc1, 0x6d,
	0x24, 0xa8, 0x07, 0xb2, 0x56, 0x0f, 0xc9, 0xce, 0x20, 0x98, 0x0a, 0x90, 0x45, 0x45, 0x89, 0x79,
	0x29, 0xf9, 0xb9, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0xcc, 0x41, 0x50, 0x1e, 0xc8, 0xe8, 0xe4, 0xfc,
	0x94, 0xd4, 0x62, 0x09, 0x16, 0x05, 0x66, 0x0d, 0xf6, 0x20, 0x08, 0x07, 0x24, 0x5a, 0x96, 0x99,
	0x5a, 0x5e, 0x2c, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe1, 0x24, 0xb1, 0x81, 0x3d, 0x67,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x4f, 0x69, 0xf5, 0xed, 0x00, 0x00, 0x00,
}
