// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: simple.proto

/*
Package _gen is a generated protocol buffer package.

It is generated from these files:
	simple.proto

It has these top-level messages:
	Person
	Employee
	Mixed
*/
package _gen

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// example enum
type Mixed_Corpus int32

const (
	Mixed_UNIVERSAL Mixed_Corpus = 0
	Mixed_WEB       Mixed_Corpus = 1
	Mixed_IMAGES    Mixed_Corpus = 2
	Mixed_LOCAL     Mixed_Corpus = 3
	Mixed_NEWS      Mixed_Corpus = 4
	Mixed_PRODUCTS  Mixed_Corpus = 5
	Mixed_VIDEO     Mixed_Corpus = 6
)

var Mixed_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}
var Mixed_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x Mixed_Corpus) String() string {
	return proto.EnumName(Mixed_Corpus_name, int32(x))
}
func (Mixed_Corpus) EnumDescriptor() ([]byte, []int) { return fileDescriptorSimple, []int{2, 0} }

// Person is a simple structure to start parsing
type Person struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age   int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptorSimple, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// Employee shows embedding on structure
type Employee struct {
	Title  string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Person *Person `protobuf:"bytes,2,opt,name=person" json:"person,omitempty"`
}

func (m *Employee) Reset()                    { *m = Employee{} }
func (m *Employee) String() string            { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()               {}
func (*Employee) Descriptor() ([]byte, []int) { return fileDescriptorSimple, []int{1} }

func (m *Employee) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Employee) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

// Mixed tries to express all basic protobuf fields
// Use to test we support all types
type Mixed struct {
	Dbl  float64      `protobuf:"fixed64,1,opt,name=dbl,proto3" json:"dbl,omitempty"`
	Flt  float32      `protobuf:"fixed32,2,opt,name=flt,proto3" json:"flt,omitempty"`
	I32  int32        `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64  int64        `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	U32  uint32       `protobuf:"varint,5,opt,name=u32,proto3" json:"u32,omitempty"`
	U64  uint64       `protobuf:"varint,6,opt,name=u64,proto3" json:"u64,omitempty"`
	S32  int32        `protobuf:"zigzag32,7,opt,name=s32,proto3" json:"s32,omitempty"`
	S64  int64        `protobuf:"zigzag64,8,opt,name=s64,proto3" json:"s64,omitempty"`
	F32  uint32       `protobuf:"fixed32,9,opt,name=f32,proto3" json:"f32,omitempty"`
	F64  uint64       `protobuf:"fixed64,10,opt,name=f64,proto3" json:"f64,omitempty"`
	Sf32 int32        `protobuf:"fixed32,11,opt,name=sf32,proto3" json:"sf32,omitempty"`
	Sf64 int64        `protobuf:"fixed64,12,opt,name=sf64,proto3" json:"sf64,omitempty"`
	B    bool         `protobuf:"varint,13,opt,name=b,proto3" json:"b,omitempty"`
	S    string       `protobuf:"bytes,14,opt,name=s,proto3" json:"s,omitempty"`
	Bz   []byte       `protobuf:"bytes,15,opt,name=bz,proto3" json:"bz,omitempty"`
	En   Mixed_Corpus `protobuf:"varint,16,opt,name=en,proto3,enum=_gen.Mixed_Corpus" json:"en,omitempty"`
}

func (m *Mixed) Reset()                    { *m = Mixed{} }
func (m *Mixed) String() string            { return proto.CompactTextString(m) }
func (*Mixed) ProtoMessage()               {}
func (*Mixed) Descriptor() ([]byte, []int) { return fileDescriptorSimple, []int{2} }

func (m *Mixed) GetDbl() float64 {
	if m != nil {
		return m.Dbl
	}
	return 0
}

func (m *Mixed) GetFlt() float32 {
	if m != nil {
		return m.Flt
	}
	return 0
}

func (m *Mixed) GetI32() int32 {
	if m != nil {
		return m.I32
	}
	return 0
}

func (m *Mixed) GetI64() int64 {
	if m != nil {
		return m.I64
	}
	return 0
}

func (m *Mixed) GetU32() uint32 {
	if m != nil {
		return m.U32
	}
	return 0
}

func (m *Mixed) GetU64() uint64 {
	if m != nil {
		return m.U64
	}
	return 0
}

func (m *Mixed) GetS32() int32 {
	if m != nil {
		return m.S32
	}
	return 0
}

func (m *Mixed) GetS64() int64 {
	if m != nil {
		return m.S64
	}
	return 0
}

func (m *Mixed) GetF32() uint32 {
	if m != nil {
		return m.F32
	}
	return 0
}

func (m *Mixed) GetF64() uint64 {
	if m != nil {
		return m.F64
	}
	return 0
}

func (m *Mixed) GetSf32() int32 {
	if m != nil {
		return m.Sf32
	}
	return 0
}

func (m *Mixed) GetSf64() int64 {
	if m != nil {
		return m.Sf64
	}
	return 0
}

func (m *Mixed) GetB() bool {
	if m != nil {
		return m.B
	}
	return false
}

func (m *Mixed) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Mixed) GetBz() []byte {
	if m != nil {
		return m.Bz
	}
	return nil
}

func (m *Mixed) GetEn() Mixed_Corpus {
	if m != nil {
		return m.En
	}
	return Mixed_UNIVERSAL
}

func init() {
	proto.RegisterType((*Person)(nil), "_gen.Person")
	proto.RegisterType((*Employee)(nil), "_gen.Employee")
	proto.RegisterType((*Mixed)(nil), "_gen.Mixed")
	proto.RegisterEnum("_gen.Mixed_Corpus", Mixed_Corpus_name, Mixed_Corpus_value)
}

func init() { proto.RegisterFile("simple.proto", fileDescriptorSimple) }

var fileDescriptorSimple = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x92, 0x4f, 0x6f, 0x9b, 0x4c,
	0x10, 0xc6, 0xdf, 0xe1, 0x9f, 0xf1, 0x04, 0x3b, 0xfb, 0xae, 0x7a, 0xd8, 0xe3, 0x0a, 0xf5, 0xb0,
	0x27, 0x1f, 0x00, 0x71, 0x77, 0x6d, 0x5a, 0x59, 0x72, 0xe2, 0x68, 0xdc, 0x24, 0x52, 0x2f, 0x95,
	0x51, 0xb6, 0x11, 0x12, 0x06, 0x64, 0x1c, 0xa9, 0xcd, 0x97, 0xe8, 0x57, 0xae, 0x66, 0x69, 0x6f,
	0xbf, 0xf9, 0x31, 0xcc, 0x83, 0x1e, 0x81, 0xc9, 0xd8, 0x9c, 0x87, 0xd6, 0xae, 0x86, 0x4b, 0x7f,
	0xed, 0x65, 0xf0, 0xfd, 0xd5, 0x76, 0xe9, 0x16, 0xa3, 0x07, 0x7b, 0x19, 0xfb, 0x4e, 0x4a, 0x0c,
	0xba, 0xd3, 0xd9, 0x2a, 0xd0, 0x60, 0xe6, 0xe4, 0x58, 0x0a, 0xf4, 0x4f, 0xaf, 0x56, 0x79, 0x1a,
	0x4c, 0x48, 0x8c, 0xf2, 0x03, 0x86, 0xf6, 0x7c, 0x6a, 0x5a, 0xe5, 0xbb, 0xb5, 0x69, 0x48, 0x3f,
	0x63, 0x5c, 0x9d, 0x87, 0xb6, 0xff, 0x65, 0xdd, 0xc6, 0xb5, 0xb9, 0xb6, 0xff, 0x0e, 0x4d, 0x83,
	0xfc, 0x88, 0xd1, 0xe0, 0x72, 0xdc, 0xb1, 0x9b, 0x2c, 0x59, 0x71, 0xfc, 0x6a, 0xca, 0xa6, 0xbf,
	0xcf, 0xd2, 0xdf, 0x3e, 0x86, 0x77, 0xcd, 0x4f, 0xfb, 0xc2, 0xc9, 0x2f, 0x75, 0xeb, 0x6e, 0x00,
	0x31, 0xb2, 0xf9, 0xd1, 0x5e, 0xdd, 0xeb, 0x1e, 0x31, 0xb2, 0x69, 0xf2, 0xcc, 0x7d, 0x49, 0x48,
	0x8c, 0xce, 0x94, 0x85, 0x0a, 0x34, 0x18, 0x9f, 0x18, 0xd9, 0xbc, 0xe5, 0x99, 0x0a, 0x35, 0x98,
	0x05, 0x31, 0x3a, 0x53, 0x16, 0x2a, 0xd2, 0x60, 0x02, 0x62, 0x64, 0x33, 0xe6, 0x99, 0x9a, 0x69,
	0x30, 0xff, 0x13, 0xa3, 0x33, 0x65, 0xa1, 0x62, 0x0d, 0x46, 0x12, 0xa3, 0x4b, 0xcf, 0x33, 0x35,
	0xd7, 0x60, 0x66, 0xc4, 0xe8, 0x4c, 0x59, 0x28, 0xd4, 0x60, 0x22, 0x62, 0xe4, 0x06, 0x47, 0x5e,
	0xba, 0xd1, 0x60, 0x6e, 0xc9, 0xf1, 0xe4, 0xca, 0x42, 0x25, 0x1a, 0x8c, 0x20, 0xc7, 0x32, 0x41,
	0xa8, 0xd5, 0x42, 0x83, 0x89, 0x09, 0x6a, 0x9e, 0x46, 0xb5, 0x74, 0x5d, 0xc1, 0x28, 0x97, 0xe8,
	0xd5, 0xef, 0xea, 0x56, 0x83, 0x49, 0xc8, 0xab, 0xdf, 0x65, 0x8a, 0x9e, 0xed, 0x94, 0xd0, 0x60,
	0x96, 0x99, 0x9c, 0x3a, 0x73, 0x05, 0xad, 0x36, 0xfd, 0x65, 0x78, 0x1b, 0xc9, 0xb3, 0x5d, 0xfa,
	0x0d, 0xa3, 0x69, 0x92, 0x0b, 0x9c, 0x3f, 0xde, 0xef, 0x9e, 0x2a, 0x3a, 0xae, 0xf7, 0xe2, 0x3f,
	0x39, 0x43, 0xff, 0xb9, 0xfa, 0x24, 0x40, 0x22, 0x46, 0xbb, 0xbb, 0xf5, 0x97, 0xea, 0x28, 0x3c,
	0x39, 0xc7, 0x70, 0x7f, 0xd8, 0xac, 0xf7, 0xc2, 0x97, 0x31, 0x06, 0xf7, 0xd5, 0xf3, 0x51, 0x04,
	0x32, 0xc1, 0xf8, 0x81, 0x0e, 0xdb, 0xc7, 0xcd, 0xd7, 0xa3, 0x08, 0x79, 0xe5, 0x69, 0xb7, 0xad,
	0x0e, 0x22, 0xaa, 0x23, 0xf7, 0xb3, 0xe4, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x28, 0x1b, 0xfe,
	0xd1, 0x3c, 0x02, 0x00, 0x00,
}
